export type BlogTable = {
  caption: string
  headers: string[]
  rows: string[][]
}

export type StaticBlog = {
  slug: string
  title: string
  excerpt: string
  category: string
  date: string
  readTime: string
  author: string
  tags: string[]
  image: string
  sections: { heading: string; paragraphs: string[]; bullets?: string[]; table?: BlogTable }[]
}

const author = "CET TEST Editorial Team"
const image = "/current-affairs-news.jpg"

export const staticBlogs: StaticBlog[] = [
  {
    slug: "government-exam-preparation-guide-for-aspirants",
    title: "Government Exam Preparation Guide: Build a System That Actually Works",
    excerpt: "A complete, practical guide to choosing an exam, understanding the syllabus, building a daily routine, revising intelligently and improving through mock tests.",
    category: "Exam Fundamentals",
    date: "September 28, 2026",
    readTime: "18 min read",
    author,
    tags: ["Government Exams", "Study Plan", "Mock Tests", "Revision"],
    image,
    sections: [
      { heading: "Preparation begins with clarity, not pressure", paragraphs: ["Government exam preparation can feel confusing because aspirants often prepare for several notifications at the same time. One examination may include reasoning, quantitative aptitude, language, general awareness, computer knowledge and a state-specific section. The solution is not to study everything randomly. Start by selecting a primary target and keeping one secondary target only when its syllabus overlaps substantially.", "Read the official notification and syllabus before buying books or joining a course. Note the eligibility, selection stages, question count, time limit, marking scheme, language, document requirements and previous-year cut-off trends. This information turns a vague goal into a measurable project. Write your target exam and expected attempt window on the first page of your notebook; every study decision should support it."], table: { caption: "First-day exam audit", headers: ["What to check", "Why it matters", "Your action"], rows: [["Syllabus", "Prevents irrelevant study", "Make a topic checklist"], ["Exam pattern", "Guides time and attempt strategy", "Create a section plan"], ["Previous papers", "Shows real question level", "Solve one diagnostic paper"], ["Eligibility and dates", "Avoids preventable mistakes", "Save the official notice"]] } },
      { heading: "Make a realistic daily study system", paragraphs: ["A strong timetable is not a poster with fourteen perfect hours. It is a repeatable routine that survives college, work, travel and low-energy days. Divide your available time into learning, practice and review. Learning explains a concept, practice builds speed and review protects what you already studied. If you have four hours, use two hours for concepts and questions, one hour for language or general awareness, and one hour for revision and error analysis.", "Keep a small daily target instead of measuring only hours. For example, complete one arithmetic topic, solve thirty reasoning questions, revise twenty current-affairs facts and analyse yesterday's mistakes. Put the phone outside the study area, use a timer for focused blocks and take a short break between blocks. Missed days should be recovered calmly; do not double the next day's workload and create another failure cycle."], table: { caption: "A flexible four-hour routine", headers: ["Block", "Work", "Output"], rows: [["Block 1", "Quantitative aptitude or reasoning", "One concept plus 25 questions"], ["Block 2", "English or Hindi", "Rules, vocabulary and practice"], ["Block 3", "General and state awareness", "Short notes and recall"], ["Block 4", "Revision and analysis", "Error log updated"]] } },
      { heading: "Use revision and mock tests as one loop", paragraphs: ["Reading a chapter once creates familiarity, not exam-ready memory. Revise new material after one day, again after three days and again after seven days. During each revision, close the book and recall the formula, definition, date or method before checking it. Active recall feels slower than rereading, but it reveals exactly what your brain can reproduce under pressure.", "Begin mock tests before completing the entire syllabus. At first, use sectional tests to learn question types. Later, take full tests in the same time slot as the real examination. Never record only the score. Record accuracy, unattempted questions, slow questions and avoidable errors. A mock is useful only when its mistakes become a practice list for the following week."], table: { caption: "Mock-test analysis sheet", headers: ["Error type", "Meaning", "Correction"], rows: [["Concept gap", "Method was unknown", "Study concept and solve examples"], ["Calculation error", "Method was right", "Practise slower, cleaner steps"], ["Time loss", "Question consumed too long", "Set a skip rule"], ["Guess or rush", "Decision was careless", "Improve reading and selection"]] } },
      { heading: "Protect accuracy, health and confidence", paragraphs: ["Most aspirants do not lose marks because they are incapable; they lose marks because their preparation is scattered. Changing books every week, watching strategy videos instead of solving questions and comparing daily scores with other students all reduce productive focus. Choose one main resource per subject, one question bank and one dependable mock series. Add resources only when a specific weakness demands them.", "Sleep is part of preparation because recall, attention and calculation depend on rest. Eat normally, walk for a few minutes and keep one lighter study session each week. Confidence should come from evidence: completed topics, improved accuracy, analysed tests and repeated revision. On exam day, read instructions carefully, secure easy marks first and leave a question when the method is not clear."], bullets: ["Study the syllabus before the study material.", "Prefer active recall over passive rereading.", "Analyse every mock, including high-scoring ones.", "Use an error notebook as a personalised syllabus.", "Keep the final week for revision, not resource hunting."] },
    ],
  },
  {
    slug: "haryana-cet-complete-preparation-guide",
    title: "Haryana CET Complete Preparation Guide: Syllabus, Strategy and Smart Practice",
    excerpt: "Understand the Haryana CET preparation approach, Haryana GK priorities, common subjects, mock-test method and a practical week-by-week plan.",
    category: "Haryana CET",
    date: "September 25, 2026",
    readTime: "20 min read",
    author,
    tags: ["Haryana CET", "Haryana GK", "HSSC", "Preparation Plan"],
    image,
    sections: [
      { heading: "What Haryana CET preparation should cover", paragraphs: ["Haryana CET aspirants need a balanced strategy because the paper rewards both general aptitude and familiarity with Haryana. Exact post-wise requirements and the latest pattern should always be checked in the current HSSC notification. For preparation, create separate folders for general awareness, reasoning, quantitative aptitude, language, computer awareness and Haryana-specific knowledge. This structure makes revision faster when the examination date is announced.", "Do not treat Haryana GK as a last-week subject. It includes connected facts about the state's history, geography, administration, culture, economy, sports and important personalities. Study one theme at a time and attach facts to a district, map, timeline or event. The goal is quick recognition in an objective paper, not writing long descriptive answers."], table: { caption: "Haryana CET preparation map", headers: ["Area", "Important focus", "Best practice"], rows: [["Haryana GK", "History, geography, culture, schemes", "One-line notes and quizzes"], ["Reasoning", "Series, coding, analogy, logic", "Timed mixed sets"], ["Quant", "Arithmetic, percentage, ratio, data", "Formula plus calculation drills"], ["Language", "Grammar, vocabulary, comprehension", "Daily reading and practice"], ["Computer", "Basics, internet, office tools", "Short factual revision"]] } },
      { heading: "Haryana GK: turn a large syllabus into small maps", paragraphs: ["Begin with Haryana's districts and physical geography. Learn rivers, canals, soils, crops, national parks, important cities and neighbouring states together rather than as disconnected lists. Next build a history timeline covering ancient sites, medieval developments, the freedom movement, formation of Haryana and important regional movements. Timelines help you separate similar names and dates.", "For culture, revise folk dances, music, fairs, festivals, language varieties, crafts, dress and notable personalities. For the present-day section, track state schemes, awards, sports achievements, appointments and important infrastructure through reliable sources. Keep a date on every current-affairs note and revise only the relevant period mentioned in the notification. Convert long material into question-answer cards because objective exams test recall speed."], table: { caption: "Haryana GK revision checklist", headers: ["Theme", "Questions to ask yourself", "Revision format"], rows: [["Geography", "Where is it and why is it important?", "Map and comparison table"], ["History", "What happened before and after it?", "Chronological timeline"], ["Culture", "Which place, community or event?", "Flashcards"], ["Government", "What is the purpose and department?", "Scheme table"], ["Current affairs", "What, when and where?", "Monthly one-liners"]] } },
      { heading: "A 12-week plan for serious aspirants", paragraphs: ["Use the first four weeks to build foundations. Complete basic arithmetic and reasoning concepts, revise core grammar and create your first Haryana GK notebook. Do not chase difficult questions before you can solve standard ones accurately. In weeks five to eight, move to mixed practice. Combine two subjects in a timed set, add previous-year questions and revise your Haryana notes every alternate day.", "Use the last four weeks for exam-mode practice. Attempt full mocks, analyse them on the same day and spend the next session repairing the weakest topic. Keep a three-page final revision file: formulas, Haryana facts and repeated mistakes. If the official pattern changes, update your plan instead of blindly following an old timetable."], table: { caption: "Twelve-week progression", headers: ["Weeks", "Main goal", "Evidence of progress"], rows: [["1–4", "Concept foundation", "Topic checklist and basic accuracy"], ["5–8", "Mixed practice", "Faster sectional scores"], ["9–10", "Full syllabus revision", "Fewer repeated errors"], ["11–12", "Mocks and final notes", "Stable attempts and timing"]] } },
      { heading: "Common Haryana CET mistakes to avoid", paragraphs: ["A common mistake is spending all preparation time on general subjects while postponing Haryana GK. Another is memorising lists without testing recall. Add ten to fifteen state-specific questions to your daily routine and revisit wrong answers every Sunday. Candidates also often attempt too many difficult questions in a mock, which produces a misleading score and poor time management. Practise leaving questions strategically.", "Remember that recruitment and eligibility rules can differ by post and notification. Treat coaching videos and social posts as explanations, not official authority. Confirm dates, qualifying conditions, syllabus updates and document requirements from the HSSC notice. On CET TEST, use topic tests to identify weaknesses and full mocks to practise the complete decision-making process."], bullets: ["Make Haryana GK a daily habit, not a final-week rescue.", "Study districts with geography, history and culture together.", "Solve official or reliable previous questions after every topic.", "Keep a separate log for calculation and reading mistakes.", "Verify the latest HSSC notice before finalising your plan."] },
    ],
  },
  {
    slug: "uksssc-exam-preparation-guide",
    title: "UKSSSC Exam Preparation Guide: Uttarakhand GK, Syllabus Planning and Revision",
    excerpt: "A clear UKSSSC preparation framework covering Uttarakhand-specific knowledge, general subjects, practice strategy and the final-month routine.",
    category: "UKSSSC",
    date: "September 22, 2026",
    readTime: "19 min read",
    author,
    tags: ["UKSSSC", "Uttarakhand GK", "Government Jobs", "Revision"],
    image,
    sections: [
      { heading: "Understand the UKSSSC exam before you study", paragraphs: ["UKSSSC examinations can be post-specific, so candidates should read the latest official advertisement for the exact eligibility, syllabus, selection stages, question pattern and marking rules. A general preparation base usually includes general studies, reasoning, quantitative aptitude, language, computer knowledge and Uttarakhand-specific general knowledge. The weight of each section may change with the post; your timetable must follow the notification rather than a generic video.", "Create a two-column syllabus sheet. In the first column, write common subjects that support multiple government exams. In the second, write the post-specific and Uttarakhand sections. Mark every topic as untouched, learning, practised or revised. This simple visual system prevents the false confidence that comes from merely highlighting pages."], table: { caption: "UKSSSC planning sheet", headers: ["Section", "Preparation question", "Useful evidence"], rows: [["Uttarakhand GK", "Can I recall place, fact and connection?", "Timed one-liner quiz"], ["General studies", "Do I understand the concept?", "Topic test"], ["Reasoning and quant", "Can I solve within time?", "Mixed timed set"], ["Language", "Can I apply the rule?", "Error-based practice"], ["Post subject", "What does the notification require?", "Official syllabus checklist"]] } },
      { heading: "Uttarakhand GK: study the state as a connected story", paragraphs: ["Uttarakhand GK becomes easier when you organise it geographically. Learn the divisions, districts, major rivers, glaciers, lakes, valleys, passes, national parks, wildlife sanctuaries and pilgrimage centres on a map. Then connect geography with agriculture, tourism, disasters, hydropower and local economy. When a fact has a location and a reason, it is easier to remember than an isolated line.", "Build a historical and cultural timeline alongside the map. Include ancient and medieval references, the Gorkha period, British administration, regional movements and the formation of the state. Revise folk traditions, fairs, festivals, languages, dances, instruments, architecture, personalities and sports. For current affairs, follow official state releases and reputable news, record the month and revise in short cycles."], table: { caption: "Uttarakhand GK framework", headers: ["Layer", "Examples of focus", "Memory aid"], rows: [["Map", "Districts, rivers, peaks, parks", "Blank map practice"], ["History", "Movements and state formation", "Timeline"], ["Culture", "Fairs, dances, languages, people", "Region-wise cards"], ["Economy", "Tourism, crops, hydropower", "Cause-and-effect notes"], ["Current affairs", "Schemes, awards, appointments", "Monthly table"]] } },
      { heading: "Build speed without sacrificing accuracy", paragraphs: ["For reasoning and quantitative aptitude, learn the standard method first, then practise faster methods only when they remain reliable. Start with percentages, ratio, average, profit and loss, simple and compound interest, time and work, time-distance, data interpretation and basic algebra as relevant to the notification. For reasoning, cover analogy, series, classification, coding, blood relations, direction, syllogism, ranking and non-verbal patterns.", "Language improves through daily contact. Read a short editorial or quality article, note unfamiliar words and solve grammar questions from the same rule. Do not memorise vocabulary without using it in a sentence. Computer preparation should be factual and regular: operating-system basics, hardware, software, internet, cyber safety, office applications and shortcuts. Ten focused questions daily are more effective than a long session once a month."], table: { caption: "Weekly practice balance", headers: ["Day", "Priority practice", "Revision task"], rows: [["Mon–Tue", "Quant and reasoning", "Formula and mistake review"], ["Wed", "Language and computer", "Vocabulary recall"], ["Thu", "Uttarakhand GK", "Map and timeline"], ["Fri", "General studies", "One-page summaries"], ["Sat", "Full mock", "Mark uncertain questions"], ["Sun", "Mock analysis", "Repair two weak topics"]] } },
      { heading: "Final month and exam-day strategy", paragraphs: ["In the final month, stop expanding your resource list. Revise your Uttarakhand notebook repeatedly, complete previous questions and take full mocks under the expected time limit. After every mock, calculate section-wise accuracy and identify whether your score is limited by knowledge, speed or selection. Repair one cause at a time; trying to fix everything in one day creates anxiety without progress.", "Keep the last three days light and familiar. Read short notes, revise formulas, check your admit card and documents, and plan your route. During the test, scan the paper first, begin with your strongest section and use a skip rule for time-consuming questions. Read the marking instructions carefully because guessing strategy depends on the current notification."], bullets: ["Always verify the current UKSSSC notification and post-wise syllabus.", "Use maps and timelines for Uttarakhand GK.", "Practise a mixed set every week to build switching ability.", "Analyse attempts and accuracy, not only the total score.", "Keep your final notes short enough to revise several times."] },
    ],
  },
  {
    slug: "haryana-cet-vs-uksssc-study-plan",
    title: "Haryana CET vs UKSSSC: How to Plan When You Are Preparing for State Exams",
    excerpt: "Compare overlapping subjects, state-specific sections and study methods so you can prepare for Haryana CET and UKSSSC without duplicating effort.",
    category: "Strategy Comparison",
    date: "September 16, 2026",
    readTime: "17 min read",
    author,
    tags: ["Haryana CET", "UKSSSC", "Study Comparison", "State Exams"],
    image,
    sections: [
      { heading: "Two state exams, one organised foundation", paragraphs: ["Preparing for Haryana CET and UKSSSC together is possible when you separate common preparation from state-specific preparation. Reasoning, arithmetic, language, computer basics and broad general awareness can be studied in shared blocks. Haryana GK and Uttarakhand GK must remain separate because mixing districts, rivers, schemes and cultural facts creates avoidable confusion.", "First compare the current official notifications. The same subject name can carry a different depth, question style or weight in two exams. Make a master spreadsheet with three labels: common, Haryana-only and Uttarakhand-only. Study common topics once, but practise them with the style and time pressure of each target paper."], table: { caption: "Where the syllabi overlap", headers: ["Preparation area", "Shared approach", "Separate work"], rows: [["Reasoning", "Concepts and timed sets", "Post-wise question level"], ["Quant", "Formula notebook", "Speed and paper pattern"], ["Language", "Daily grammar and reading", "Hindi/English emphasis"], ["Computer", "Basics and shortcuts", "Notification-specific topics"], ["State GK", "Short-note method", "Haryana and Uttarakhand files"]] } },
      { heading: "Build a two-target weekly timetable", paragraphs: ["Do not alternate entire weeks between states. Keep common subjects active every day and rotate the state-specific section. For example, use the first study block for arithmetic or reasoning, the second for language or computer, and the third for a state section. Give Haryana and Uttarakhand equal attention only when their exam dates and expected importance are comparable; otherwise adjust the ratio based on the nearer notification.", "Every Saturday, take one full mock for the nearer exam and use a shorter sectional test for the other. On Sunday, analyse both. Maintain separate score sheets and separate error pages. This prevents a good score in one paper from hiding a weakness in the other."], table: { caption: "Sample combined timetable", headers: ["Day", "Common block", "State block"], rows: [["Monday", "Arithmetic and language", "Haryana geography"], ["Tuesday", "Reasoning and computer", "Uttarakhand history"], ["Wednesday", "Arithmetic and reasoning", "Haryana culture"], ["Thursday", "Language and GA", "Uttarakhand geography"], ["Friday", "Mixed practice", "Both state current affairs"], ["Saturday", "Target-exam mock", "Other exam sectional test"], ["Sunday", "Analysis and revision", "Weak-topic repair"]] } },
      { heading: "Avoid confusion with visual notes", paragraphs: ["Use different notebook covers or digital folders for each state. Every fact should carry a label such as Haryana—history or Uttarakhand—geography. Revise one state at a time during a session instead of jumping between both every few minutes. Maps are especially useful: draw a blank outline, place key rivers and districts, then check your work.", "For current affairs, maintain monthly tables with columns for event, department or location, date and possible question. At the end of the month, remove duplicate facts and keep only examinable information. The same revision technique works for both states, but the content must remain clearly separated."], table: { caption: "Anti-confusion note format", headers: ["Field", "Example format", "Benefit"], rows: [["State label", "HR or UK in heading", "Prevents mixing"], ["Topic", "River, scheme, person", "Enables filtering"], ["Location", "District or region", "Builds context"], ["Date", "Month and year", "Supports current affairs"], ["Source", "Official notice or trusted news", "Improves reliability"]] } },
      { heading: "Decide what to prioritise", paragraphs: ["When two examinations approach together, prioritise the one with the earlier date or the larger overlap. Do not abandon the second completely; keep it alive with short daily revision and one weekly test. If the exams have different marking schemes, practise decision-making separately. A safe attempt in a paper with negative marking is not the same as a maximum attempt in a paper without it.", "Your final revision should be exam-specific. Prepare one Haryana quick file and one Uttarakhand quick file, plus a shared file for formulas, grammar and computer basics. The night before each exam, revise only the relevant file and instructions. Clear organisation turns a double-target plan from a burden into an advantage."], bullets: ["Study shared subjects once, then test them in each paper style.", "Never combine Haryana and Uttarakhand facts in one list.", "Use separate mock-score sheets and error logs.", "Give more time to the earlier or more important examination.", "Confirm marking rules from the current notification before choosing attempts."] },
    ],
  },
  {
    slug: "mock-test-analysis-and-final-revision-plan",
    title: "Mock Tests and Final Revision: The Complete Score-Improvement Method",
    excerpt: "Learn how to use mock tests, error logs, revision tables and exam-day practice to convert preparation into reliable marks.",
    category: "Mock Tests",
    date: "September 10, 2026",
    readTime: "16 min read",
    author,
    tags: ["Mock Tests", "Final Revision", "Score Improvement", "Exam Strategy"],
    image,
    sections: [
      { heading: "A mock test is a diagnostic, not a judgement", paragraphs: ["A low mock score is information about your current system, not a final statement about your ability. Take each test under realistic conditions: fixed time, no phone, permitted stationery and no checking answers midway. Use the same section order that you may use in the real exam, then change the order in a later test to discover which approach suits you.", "Before starting, write down a target for accuracy and a target for attempts. After the test, compare the result with both targets. A higher attempt count is not improvement if accuracy falls. The best strategy is the one that gives you stable marks across several tests, not one lucky score."], table: { caption: "What to record after every mock", headers: ["Metric", "Question to ask", "Next action"], rows: [["Accuracy", "Which section lost marks?", "Revise its error topics"], ["Time", "Where did minutes disappear?", "Set section limits"], ["Attempts", "Did I skip too little?", "Use a skip rule"], ["Errors", "Were they avoidable?", "Slow down at trigger points"], ["Confidence", "Which section felt uncertain?", "Take a sectional test"]] } },
      { heading: "The four-pass analysis method", paragraphs: ["Pass one is the score pass: record correct, incorrect, unattempted and marked-for-review questions. Pass two is the time pass: identify questions that consumed too many minutes and sections where you rushed near the end. Pass three is the concept pass: for every wrong question, write the missing rule or method in your own words. Pass four is the repeat pass: solve the same question again after a gap without seeing the solution.", "Do not copy long explanations into your error notebook. Write the smallest useful reminder, such as ‘check unit conversion’ or ‘read the inequality direction’. Group repeated reminders. If the same error appears three times, it is not bad luck; it is a topic requiring a dedicated practice session."], table: { caption: "Error-log template", headers: ["Question", "Reason for error", "Repair task", "Review date"], rows: [["Q number", "Concept / speed / rush", "10 similar questions", "After 3 days"], ["Q number", "Misread condition", "Underline key words", "Next mock"], ["Q number", "Forgot fact", "Add flashcard", "Sunday"]] } },
      { heading: "A 30-day final revision calendar", paragraphs: ["In days 30 to 21, finish remaining high-priority concepts and take two full mocks each week. In days 20 to 11, increase to three mocks if analysis is still possible, revise state GK and practise language daily. In days 10 to 4, stop collecting new material and revise your short files, formulas, maps, timelines and repeated mistakes. In the final three days, reduce volume and protect sleep.", "Use tables rather than large notebooks for final revision. A table lets you compare similar facts, identify missing columns and revise a complete topic quickly. For Haryana CET, include Haryana-specific facts and the current official pattern. For UKSSSC, include Uttarakhand maps, history, culture and current affairs. Always update both from the latest notification."], table: { caption: "Final-month rhythm", headers: ["Period", "Mocks", "Main revision", "Goal"], rows: [["Days 30–21", "2 per week", "Finish priority topics", "Close syllabus gaps"], ["Days 20–11", "2–3 per week", "State GK and mixed sets", "Improve stability"], ["Days 10–4", "2 per week", "Short notes and mistakes", "Protect accuracy"], ["Days 3–1", "No heavy mock", "Light recall and logistics", "Arrive fresh"]] } },
      { heading: "Exam-day decisions that protect your score", paragraphs: ["Read the instructions before solving. Check whether there is negative marking, how unattempted questions must be recorded and whether the paper is bilingual. Start with a section where you can collect marks confidently, but do not spend the first minutes proving that you can solve one difficult question. Mark time checkpoints and move on when a question has crossed your planned limit.", "After the exam, avoid immediately judging your performance from memory or social-media discussions. Note the questions you remember only if it helps a later analysis, then wait for the official answer key and notice. Your next opportunity benefits from calm review more than emotional comparison."], bullets: ["Take mocks in exam-like conditions.", "Analyse the paper before taking the next one.", "Convert repeated mistakes into targeted sets.", "Use short tables for last-week revision.", "Confirm official instructions before the examination."] },
    ],
  },
]

export function getStaticBlog(slug: string) {
  return staticBlogs.find((blog) => blog.slug === slug)
}

export function stripMarkup(value: string) {
  return value.replace(/<[^>]*>/g, "").trim()
}

export function getBlogWords(blog: StaticBlog) {
  return blog.sections.flatMap((section) => [section.heading, ...section.paragraphs, ...(section.bullets ?? []), ...(section.table?.rows.flat() ?? [])]).join(" ").split(/\s+/).length
}

// Keep the article collection local and deterministic. It intentionally does not read from a server or database.

