// Demo questions for each test type

export interface DemoQuestion {
  id: string
  question_text: string
  option_a: string
  option_b: string
  option_c: string
  option_d: string
  correct_answer: "a" | "b" | "c" | "d"
  explanation: string
  subject: string
}

export const demoQuestions: Record<string, DemoQuestion[]> = {
  "haryana-police": [
    {
      id: "hp-1",
      question_text: "हरियाणा पुलिस का मुख्यालय कहाँ स्थित है?",
      option_a: "गुरुग्राम",
      option_b: "पंचकुला",
      option_c: "फरीदाबाद",
      option_d: "करनाल",
      correct_answer: "b",
      explanation: "हरियाणा पुलिस का मुख्यालय पंचकुला में स्थित है।",
      subject: "Haryana GK",
    },
    {
      id: "hp-2",
      question_text: "Which article of the Indian Constitution deals with the appointment of the Chief Minister?",
      option_a: "Article 163",
      option_b: "Article 164",
      option_c: "Article 165",
      option_d: "Article 166",
      correct_answer: "b",
      explanation: "Article 164 deals with the appointment of the Chief Minister and other Ministers.",
      subject: "General Knowledge",
    },
    {
      id: "hp-3",
      question_text: "If 5x + 3 = 18, then x = ?",
      option_a: "2",
      option_b: "3",
      option_c: "4",
      option_d: "5",
      correct_answer: "b",
      explanation: "5x + 3 = 18 → 5x = 15 → x = 3",
      subject: "Math",
    },
    {
      id: "hp-4",
      question_text: "Find the odd one out: 2, 5, 10, 17, 27, 37",
      option_a: "10",
      option_b: "17",
      option_c: "27",
      option_d: "37",
      correct_answer: "c",
      explanation: "The pattern is n² + 1: 1+1=2, 4+1=5, 9+1=10, 16+1=17, 25+1=26 (not 27), 36+1=37. So 27 is wrong.",
      subject: "Reasoning",
    },
    {
      id: "hp-5",
      question_text: "हरियाणा राज्य का गठन कब हुआ था?",
      option_a: "1 नवंबर 1966",
      option_b: "15 अगस्त 1966",
      option_c: "26 जनवरी 1966",
      option_d: "1 मई 1966",
      correct_answer: "a",
      explanation: "हरियाणा राज्य का गठन 1 नवंबर 1966 को पंजाब से अलग होकर हुआ था।",
      subject: "Haryana GK",
    },
    {
      id: "hp-6",
      question_text: "The Supreme Court of India was established on:",
      option_a: "26 January 1950",
      option_b: "28 January 1950",
      option_c: "15 August 1947",
      option_d: "26 November 1949",
      correct_answer: "b",
      explanation: "The Supreme Court of India was inaugurated on 28 January 1950.",
      subject: "General Knowledge",
    },
    {
      id: "hp-7",
      question_text: "A train 150m long passes a pole in 15 seconds. What is the speed of the train in km/hr?",
      option_a: "36 km/hr",
      option_b: "40 km/hr",
      option_c: "45 km/hr",
      option_d: "50 km/hr",
      correct_answer: "a",
      explanation: "Speed = Distance/Time = 150/15 = 10 m/s = 10 × 18/5 = 36 km/hr",
      subject: "Math",
    },
    {
      id: "hp-8",
      question_text: "If COMPUTER is coded as RFUVQNPC, then MEDICINE is coded as:",
      option_a: "MFEDJDJO",
      option_b: "ENICJDME",
      option_c: "FNDJDJOF",
      option_d: "ENICIDMF",
      correct_answer: "b",
      explanation: "The pattern reverses the word and shifts each letter by +1. MEDICINE → ENICIDME → ENICJDME",
      subject: "Reasoning",
    },
    {
      id: "hp-9",
      question_text: "'वीर चक्र' से सम्मानित हरियाणा का पहला जवान कौन था?",
      option_a: "मेजर होशियार सिंह",
      option_b: "कैप्टन अभिमन्यु राणा",
      option_c: "सूबेदार योगेंद्र सिंह यादव",
      option_d: "नायक सुरेंद्र सिंह",
      correct_answer: "a",
      explanation: "मेजर होशियार सिंह 'वीर चक्र' से सम्मानित हरियाणा के पहले जवान थे।",
      subject: "Haryana GK",
    },
    {
      id: "hp-10",
      question_text: "'संविधान सभा' के अध्यक्ष कौन थे?",
      option_a: "डॉ. राजेंद्र प्रसाद",
      option_b: "डॉ. बी.आर. अंबेडकर",
      option_c: "पंडित जवाहरलाल नेहरू",
      option_d: "सरदार वल्लभभाई पटेल",
      correct_answer: "a",
      explanation: "डॉ. राजेंद्र प्रसाद संविधान सभा के स्थायी अध्यक्ष थे।",
      subject: "General Knowledge",
    },
  ],
  "haryana-group-d": [
    {
      id: "gd-1",
      question_text: "हरियाणा की राजधानी क्या है?",
      option_a: "गुरुग्राम",
      option_b: "चंडीगढ़",
      option_c: "फरीदाबाद",
      option_d: "पानीपत",
      correct_answer: "b",
      explanation: "चंडीगढ़ हरियाणा और पंजाब दोनों राज्यों की संयुक्त राजधानी है।",
      subject: "Haryana GK",
    },
    {
      id: "gd-2",
      question_text: "हरियाणा में कुल कितने जिले हैं?",
      option_a: "20",
      option_b: "21",
      option_c: "22",
      option_d: "23",
      correct_answer: "c",
      explanation: "हरियाणा में वर्तमान में 22 जिले हैं।",
      subject: "Haryana GK",
    },
    {
      id: "gd-3",
      question_text: "2 + 2 × 2 = ?",
      option_a: "4",
      option_b: "6",
      option_c: "8",
      option_d: "10",
      correct_answer: "b",
      explanation: "BODMAS नियम के अनुसार: पहले गुणा 2 × 2 = 4, फिर जोड़ 2 + 4 = 6",
      subject: "Basic Math",
    },
    {
      id: "gd-4",
      question_text: "भारत का राष्ट्रीय पक्षी कौन सा है?",
      option_a: "कौआ",
      option_b: "मोर",
      option_c: "तोता",
      option_d: "कबूतर",
      correct_answer: "b",
      explanation: "मोर भारत का राष्ट्रीय पक्षी है।",
      subject: "General Awareness",
    },
    {
      id: "gd-5",
      question_text: "अगर किसी महीने की 3 तारीख को सोमवार है, तो उसी महीने की 21 तारीख को कौन सा दिन होगा?",
      option_a: "शुक्रवार",
      option_b: "शनिवार",
      option_c: "रविवार",
      option_d: "सोमवार",
      correct_answer: "a",
      explanation: "3 से 21 = 18 दिन = 2 सप्ताह + 4 दिन। सोमवार + 4 = शुक्रवार",
      subject: "Reasoning",
    },
    {
      id: "gd-6",
      question_text: "हरियाणा का राज्य पशु कौन सा है?",
      option_a: "शेर",
      option_b: "हाथी",
      option_c: "नीलगाय",
      option_d: "काला हिरण",
      correct_answer: "d",
      explanation: "काला हिरण (Black Buck) हरियाणा का राज्य पशु है।",
      subject: "Haryana GK",
    },
    {
      id: "gd-7",
      question_text: "100 का 25% कितना होगा?",
      option_a: "20",
      option_b: "25",
      option_c: "30",
      option_d: "35",
      correct_answer: "b",
      explanation: "100 का 25% = (100 × 25)/100 = 25",
      subject: "Basic Math",
    },
    {
      id: "gd-8",
      question_text: "भारत का संविधान कब लागू हुआ?",
      option_a: "15 अगस्त 1947",
      option_b: "26 नवंबर 1949",
      option_c: "26 जनवरी 1950",
      option_d: "2 अक्टूबर 1950",
      correct_answer: "c",
      explanation: "भारत का संविधान 26 जनवरी 1950 को लागू हुआ।",
      subject: "General Awareness",
    },
    {
      id: "gd-9",
      question_text: "निम्न में से कौन सी संख्या 3 से विभाज्य है?",
      option_a: "124",
      option_b: "235",
      option_c: "126",
      option_d: "238",
      correct_answer: "c",
      explanation: "126 के अंकों का योग 1+2+6 = 9, जो 3 से विभाज्य है।",
      subject: "Basic Math",
    },
    {
      id: "gd-10",
      question_text: "सुल्तानपुर राष्ट्रीय उद्यान हरियाणा के किस जिले में है?",
      option_a: "गुरुग्राम",
      option_b: "फरीदाबाद",
      option_c: "हिसार",
      option_d: "रोहतक",
      correct_answer: "a",
      explanation: "सुल्तानपुर राष्ट्रीय उद्यान गुरुग्राम जिले में स्थित है।",
      subject: "Haryana GK",
    },
  ],
  "haryana-cet": [
    {
      id: "cet-1",
      question_text: "हरियाणा का क्षेत्रफल कितना है?",
      option_a: "44,212 वर्ग किमी",
      option_b: "45,212 वर्ग किमी",
      option_c: "46,212 वर्ग किमी",
      option_d: "47,212 वर्ग किमी",
      correct_answer: "a",
      explanation: "हरियाणा का कुल क्षेत्रफल 44,212 वर्ग किलोमीटर है।",
      subject: "Haryana GK",
    },
    {
      id: "cet-2",
      question_text: "If the ratio of ages of A and B is 3:5 and sum of their ages is 40, find A's age.",
      option_a: "12 years",
      option_b: "15 years",
      option_c: "18 years",
      option_d: "20 years",
      correct_answer: "b",
      explanation: "A's age = (3/8) × 40 = 15 years",
      subject: "Quantitative Aptitude",
    },
    {
      id: "cet-3",
      question_text: "Choose the correct spelling:",
      option_a: "Accomodation",
      option_b: "Acommodation",
      option_c: "Accommodation",
      option_d: "Acomodation",
      correct_answer: "c",
      explanation: "The correct spelling is 'Accommodation' with double 'c' and double 'm'.",
      subject: "English",
    },
    {
      id: "cet-4",
      question_text: "A, B, C, D, E में से कौन सबसे लंबा है? A, B से लंबा है। C, D से छोटा है। E, A से लंबा है। B, D से लंबा है।",
      option_a: "A",
      option_b: "B",
      option_c: "D",
      option_d: "E",
      correct_answer: "d",
      explanation: "क्रम: E > A > B > D > C, इसलिए E सबसे लंबा है।",
      subject: "Reasoning",
    },
    {
      id: "cet-5",
      question_text: "हरियाणा विधानसभा में कुल कितनी सीटें हैं?",
      option_a: "85",
      option_b: "90",
      option_c: "95",
      option_d: "100",
      correct_answer: "b",
      explanation: "हरियाणा विधानसभा में कुल 90 सीटें हैं।",
      subject: "Haryana GK",
    },
    {
      id: "cet-6",
      question_text: "A shopkeeper sells an article for ₹450 at 25% profit. Find the cost price.",
      option_a: "₹320",
      option_b: "₹340",
      option_c: "₹360",
      option_d: "₹380",
      correct_answer: "c",
      explanation: "CP = SP × 100/(100 + Profit%) = 450 × 100/125 = ₹360",
      subject: "Quantitative Aptitude",
    },
    {
      id: "cet-7",
      question_text: "Select the correct passive voice: 'She is writing a letter.'",
      option_a: "A letter is written by her",
      option_b: "A letter is being written by her",
      option_c: "A letter was being written by her",
      option_d: "A letter has been written by her",
      correct_answer: "b",
      explanation: "Present Continuous passive: Object + is/are + being + V3 + by + Subject",
      subject: "English",
    },
    {
      id: "cet-8",
      question_text: "यदि किसी कोड में BASKET को UFLTBC लिखा जाता है, तो FLOWER को कैसे लिखेंगे?",
      option_a: "SFXPMG",
      option_b: "SFXPGM",
      option_c: "SFWPMG",
      option_d: "SFWPGM",
      correct_answer: "a",
      explanation: "प्रत्येक अक्षर को उल्टा करके +1 जोड़ा गया है। FLOWER → REWOLF → SFXPMG",
      subject: "Reasoning",
    },
    {
      id: "cet-9",
      question_text: "कुरुक्षेत्र में किस महाभारत युद्ध का मैदान स्थित है?",
      option_a: "ज्योतिसर",
      option_b: "पानीपत",
      option_c: "थानेसर",
      option_d: "पिपली",
      correct_answer: "a",
      explanation: "ज्योतिसर कुरुक्षेत्र में स्थित वह स्थान है जहाँ भगवान कृष्ण ने अर्जुन को गीता का उपदेश दिया था।",
      subject: "Haryana GK",
    },
    {
      id: "cet-10",
      question_text:
        "A can do a work in 12 days and B can do it in 18 days. In how many days can they complete it together?",
      option_a: "6.2 days",
      option_b: "7.2 days",
      option_c: "8.2 days",
      option_d: "9.2 days",
      correct_answer: "b",
      explanation: "Combined work = 1/12 + 1/18 = 5/36. Days = 36/5 = 7.2 days",
      subject: "Quantitative Aptitude",
    },
  ],
}

  "ssc-cgl": [
    {
      id: "ssc-1",
      question_text: "If 15% of x = 20% of y, then x:y is:",
      option_a: "3:4",
      option_b: "4:3",
      option_c: "3:5",
      option_d: "5:3",
      correct_answer: "b",
      explanation: "15x = 20y → x/y = 20/15 = 4/3. So x:y = 4:3",
      subject: "Quantitative Aptitude",
    },
    {
      id: "ssc-2",
      question_text: "The Parliament of India cannot legislate on a subject in the State List unless:",
      option_a: "The President of India directs it to do so",
      option_b: "The Rajya Sabha passes a resolution by 2/3rd majority",
      option_c: "The Prime Minister advises the Parliament to do so",
      option_d: "The Supreme Court directs it",
      correct_answer: "b",
      explanation: "Under Article 249, Rajya Sabha can authorise Parliament to legislate on State subjects by a 2/3rd majority resolution.",
      subject: "General Awareness",
    },
    {
      id: "ssc-3",
      question_text: "Select the most appropriate synonym for the word 'ENIGMATIC':",
      option_a: "Obvious",
      option_b: "Mysterious",
      option_c: "Simple",
      option_d: "Friendly",
      correct_answer: "b",
      explanation: "'Enigmatic' means difficult to understand or mysterious.",
      subject: "English",
    },
    {
      id: "ssc-4",
      question_text: "Statements: All cats are dogs. All dogs are animals. Conclusions: I. All cats are animals. II. Some animals are cats.",
      option_a: "Only I follows",
      option_b: "Only II follows",
      option_c: "Both I and II follow",
      option_d: "Neither I nor II follows",
      correct_answer: "c",
      explanation: "Since All cats are dogs (A→B) and All dogs are animals (B→C), All cats are animals follows. Also, since some animals are dogs, and all dogs include cats, some animals are cats.",
      subject: "Reasoning",
    },
    {
      id: "ssc-5",
      question_text: "The speed of a boat in still water is 15 km/hr. It goes 30 km upstream and returns downstream in a total of 4.5 hours. Find the speed of stream.",
      option_a: "3 km/hr",
      option_b: "4 km/hr",
      option_c: "5 km/hr",
      option_d: "6 km/hr",
      correct_answer: "c",
      explanation: "Let stream speed = s. 30/(15-s) + 30/(15+s) = 4.5. Solving: s = 5 km/hr",
      subject: "Quantitative Aptitude",
    },
    {
      id: "ssc-6",
      question_text: "Which gas is responsible for the depletion of the ozone layer?",
      option_a: "Carbon dioxide",
      option_b: "Chlorofluorocarbon (CFC)",
      option_c: "Nitrogen dioxide",
      option_d: "Sulphur dioxide",
      correct_answer: "b",
      explanation: "Chlorofluorocarbons (CFCs) released from refrigerants and aerosols are responsible for ozone layer depletion.",
      subject: "General Awareness",
    },
    {
      id: "ssc-7",
      question_text: "Choose the correctly spelt word:",
      option_a: "Harrass",
      option_b: "Harass",
      option_c: "Harras",
      option_d: "Harasss",
      correct_answer: "b",
      explanation: "The correct spelling is 'Harass' — one 'r' and two 's'.",
      subject: "English",
    },
    {
      id: "ssc-8",
      question_text: "In a certain code, MANGO is written as OCPIQ. How is GRAPE written?",
      option_a: "ITCQF",
      option_b: "ITCRG",
      option_c: "IRCQG",
      option_d: "IUCRG",
      correct_answer: "b",
      explanation: "Each letter is shifted forward by +2. G+2=I, R+2=T, A+2=C, P+2=R, E+2=G → ITCRG",
      subject: "Reasoning",
    },
    {
      id: "ssc-9",
      question_text: "The compound interest on ₹8000 at 10% per annum for 2 years is:",
      option_a: "₹1,600",
      option_b: "₹1,680",
      option_c: "₹1,720",
      option_d: "₹1,760",
      correct_answer: "b",
      explanation: "CI = P[(1+r/100)^n - 1] = 8000[(1.1)^2 - 1] = 8000[1.21 - 1] = 8000 × 0.21 = ₹1,680",
      subject: "Quantitative Aptitude",
    },
    {
      id: "ssc-10",
      question_text: "Which of the following is NOT a Fundamental Right under the Indian Constitution?",
      option_a: "Right to Equality",
      option_b: "Right to Property",
      option_c: "Right to Freedom of Religion",
      option_d: "Right against Exploitation",
      correct_answer: "b",
      explanation: "Right to Property was removed from Fundamental Rights by the 44th Amendment Act, 1978 and made a legal right under Article 300A.",
      subject: "General Awareness",
    },
  ],
  "rrb-ntpc": [
    {
      id: "rrb-1",
      question_text: "Indian Railways was nationalised in which year?",
      option_a: "1947",
      option_b: "1950",
      option_c: "1951",
      option_d: "1953",
      correct_answer: "d",
      explanation: "Indian Railways was nationalised in 1953 when all private railway companies were merged under a single government entity.",
      subject: "General Awareness",
    },
    {
      id: "rrb-2",
      question_text: "A number when divided by 119 leaves a remainder 19. What will be the remainder when divided by 17?",
      option_a: "1",
      option_b: "2",
      option_c: "3",
      option_d: "5",
      correct_answer: "b",
      explanation: "119 = 7 × 17. So (119k + 19) ÷ 17 → 19 ÷ 17 = 1 remainder 2.",
      subject: "Mathematics",
    },
    {
      id: "rrb-3",
      question_text: "Which is the longest railway platform in India?",
      option_a: "Gorakhpur",
      option_b: "Kharagpur",
      option_c: "Kollam",
      option_d: "Hubballi",
      correct_answer: "d",
      explanation: "Hubballi (formerly Hubli) railway station in Karnataka has India's longest railway platform at 1,505 metres.",
      subject: "General Awareness",
    },
    {
      id: "rrb-4",
      question_text: "Fill in the blank: The committee ________ the report yesterday.",
      option_a: "submit",
      option_b: "submits",
      option_c: "submitted",
      option_d: "will submit",
      correct_answer: "c",
      explanation: "'Yesterday' indicates past tense, so 'submitted' is correct.",
      subject: "English",
    },
    {
      id: "rrb-5",
      question_text: "If South-East is called East, North-West is called West, South-West is called South, then what is North-East called?",
      option_a: "North",
      option_b: "East",
      option_c: "South",
      option_d: "West",
      correct_answer: "a",
      explanation: "Following the same pattern of shifting direction 45° clockwise, North-East becomes North.",
      subject: "Reasoning",
    },
    {
      id: "rrb-6",
      question_text: "The average of 5 consecutive even numbers is 14. The largest number is:",
      option_a: "16",
      option_b: "17",
      option_c: "18",
      option_d: "20",
      correct_answer: "c",
      explanation: "If average is 14, the middle number is 14. The 5 consecutive even numbers are 10, 12, 14, 16, 18. Largest = 18.",
      subject: "Mathematics",
    },
    {
      id: "rrb-7",
      question_text: "First Railway Budget in India was presented by:",
      option_a: "John Mathai",
      option_b: "Lal Bahadur Shastri",
      option_c: "Jagjivan Ram",
      option_d: "T.A. Pai",
      correct_answer: "a",
      explanation: "John Mathai presented the first Railway Budget of independent India in 1947.",
      subject: "General Awareness",
    },
    {
      id: "rrb-8",
      question_text: "Pointing to a photograph, a man says 'I have no brother or sister but this man's father is my father's son.' Whose photo is it?",
      option_a: "His own",
      option_b: "His father's",
      option_c: "His son's",
      option_d: "His nephew's",
      correct_answer: "c",
      explanation: "Since he has no siblings, 'my father's son' = himself. So 'this man's father = himself', meaning the photo is of his son.",
      subject: "Reasoning",
    },
    {
      id: "rrb-9",
      question_text: "A train 200m long is running at 72 km/hr. In how many seconds will it cross a bridge 400m long?",
      option_a: "25 seconds",
      option_b: "30 seconds",
      option_c: "35 seconds",
      option_d: "40 seconds",
      correct_answer: "b",
      explanation: "Total distance = 200 + 400 = 600m. Speed = 72 × 5/18 = 20 m/s. Time = 600/20 = 30 seconds.",
      subject: "Mathematics",
    },
    {
      id: "rrb-10",
      question_text: "The Konkan Railway connects which two states?",
      option_a: "Maharashtra and Karnataka",
      option_b: "Maharashtra and Goa",
      option_c: "Maharashtra to Kerala via Goa and Karnataka",
      option_d: "Goa and Karnataka only",
      correct_answer: "c",
      explanation: "Konkan Railway runs from Roha in Maharashtra to Thokur near Mangaluru in Karnataka, passing through Goa.",
      subject: "General Awareness",
    },
  ],
  "uksssc": [
    {
      id: "uk-1",
      question_text: "उत्तराखंड राज्य का गठन कब हुआ था?",
      option_a: "9 नवंबर 2000",
      option_b: "1 नवंबर 2000",
      option_c: "15 अगस्त 2000",
      option_d: "26 जनवरी 2001",
      correct_answer: "a",
      explanation: "उत्तराखंड राज्य 9 नवंबर 2000 को उत्तर प्रदेश से अलग होकर बना।",
      subject: "Uttarakhand GK",
    },
    {
      id: "uk-2",
      question_text: "उत्तराखंड की राजधानी कौन सी है?",
      option_a: "नैनीताल",
      option_b: "देहरादून",
      option_c: "हरिद्वार",
      option_d: "मसूरी",
      correct_answer: "b",
      explanation: "देहरादून उत्तराखंड की राजधानी और सबसे बड़ा शहर है।",
      subject: "Uttarakhand GK",
    },
    {
      id: "uk-3",
      question_text: "Jim Corbett National Park is located in which district of Uttarakhand?",
      option_a: "Haridwar",
      option_b: "Dehradun",
      option_c: "Nainital",
      option_d: "Pauri Garhwal",
      correct_answer: "c",
      explanation: "Jim Corbett National Park is located in Nainital district of Uttarakhand, established in 1936.",
      subject: "Uttarakhand GK",
    },
    {
      id: "uk-4",
      question_text: "The simple interest on ₹4000 at 5% per annum for 3 years is:",
      option_a: "₹500",
      option_b: "₹550",
      option_c: "₹600",
      option_d: "₹650",
      correct_answer: "c",
      explanation: "SI = (P × R × T)/100 = (4000 × 5 × 3)/100 = ₹600",
      subject: "Mathematics",
    },
    {
      id: "uk-5",
      question_text: "उत्तराखंड का राज्य पुष्प कौन सा है?",
      option_a: "गुलाब",
      option_b: "कमल",
      option_c: "ब्रह्म कमल",
      option_d: "बुरांश",
      correct_answer: "c",
      explanation: "ब्रह्म कमल (Saussurea obvallata) उत्तराखंड का राजकीय पुष्प है।",
      subject: "Uttarakhand GK",
    },
    {
      id: "uk-6",
      question_text: "In a row of 40 students, Ravi is 15th from the left. What is his position from the right?",
      option_a: "24th",
      option_b: "25th",
      option_c: "26th",
      option_d: "27th",
      correct_answer: "c",
      explanation: "Position from right = Total - Position from left + 1 = 40 - 15 + 1 = 26th",
      subject: "Reasoning",
    },
    {
      id: "uk-7",
      question_text: "Chipko Movement of Uttarakhand was started in which year?",
      option_a: "1970",
      option_b: "1973",
      option_c: "1975",
      option_d: "1980",
      correct_answer: "b",
      explanation: "The Chipko Movement started in 1973 in Gopeshwar, Chamoli district, when villagers hugged trees to prevent logging.",
      subject: "Uttarakhand GK",
    },
    {
      id: "uk-8",
      question_text: "In a row of students, Mohan is 12th from the front and 8th from the back. How many students are in the row?",
      option_a: "18",
      option_b: "19",
      option_c: "20",
      option_d: "21",
      correct_answer: "b",
      explanation: "Total students = Position from front + Position from back - 1 = 12 + 8 - 1 = 19",
      subject: "Reasoning",
    },
    {
      id: "uk-9",
      question_text: "Valley of Flowers National Park is located in which district of Uttarakhand?",
      option_a: "Uttarkashi",
      option_b: "Chamoli",
      option_c: "Rudraprayag",
      option_d: "Pithoragarh",
      correct_answer: "b",
      explanation: "Valley of Flowers National Park is located in Chamoli district of Uttarakhand and is a UNESCO World Heritage Site.",
      subject: "Uttarakhand GK",
    },
    {
      id: "uk-10",
      question_text: "The perimeter of a rectangle is 60 cm and its length is twice its breadth. Find the area.",
      option_a: "150 sq cm",
      option_b: "180 sq cm",
      option_c: "200 sq cm",
      option_d: "250 sq cm",
      correct_answer: "c",
      explanation: "Let breadth = b, length = 2b. Perimeter = 2(2b+b) = 6b = 60 → b = 10. Area = 2b × b = 2×10×10 = 200 sq cm.",
      subject: "Mathematics",
    },
  ],
}

export function getDemoTest(testId: string) {
  const questions = demoQuestions[testId]
  if (!questions) return null

  const testInfo: Record<string, { title: string; duration: number }> = {
    "haryana-police": { title: "Haryana Police Constable Demo Test", duration: 10 },
    "haryana-group-d": { title: "Haryana Group D Demo Test", duration: 10 },
    "haryana-cet": { title: "Haryana CET Demo Test", duration: 10 },
    "ssc-cgl": { title: "SSC CGL Demo Test", duration: 10 },
    "rrb-ntpc": { title: "RRB NTPC Demo Test", duration: 10 },
    "uksssc": { title: "UKSSSC Demo Test", duration: 10 },
  }

  return {
    id: testId,
    title: testInfo[testId]?.title || "Demo Test",
    duration: testInfo[testId]?.duration || 10,
    questions,
  }
}
