// Demo questions for each test type

export interface DemoQuestion {
  id: string
  question_text: string
  option_a: string
  option_b: string
  option_c: string
  option_d: string
  correct_answer: "a" | "b" | "c" | "d"
  explanation: string
  subject: string
}

export const demoQuestions: Record<string, DemoQuestion[]> = {
  "haryana-police": [
    {
      id: "hp-1",
      question_text: "हरियाणा पुलिस का मुख्यालय कहाँ स्थित है?",
      option_a: "गुरुग्राम",
      option_b: "पंचकुला",
      option_c: "फरीदाबाद",
      option_d: "करनाल",
      correct_answer: "b",
      explanation: "हरियाणा पुलिस का मुख्यालय पंचकुला में स्थित है।",
      subject: "Haryana GK",
    },
    {
      id: "hp-2",
      question_text: "Which article of the Indian Constitution deals with the appointment of the Chief Minister?",
      option_a: "Article 163",
      option_b: "Article 164",
      option_c: "Article 165",
      option_d: "Article 166",
      correct_answer: "b",
      explanation: "Article 164 deals with the appointment of the Chief Minister and other Ministers.",
      subject: "General Knowledge",
    },
    {
      id: "hp-3",
      question_text: "If 5x + 3 = 18, then x = ?",
      option_a: "2",
      option_b: "3",
      option_c: "4",
      option_d: "5",
      correct_answer: "b",
      explanation: "5x + 3 = 18 → 5x = 15 → x = 3",
      subject: "Math",
    },
    {
      id: "hp-4",
      question_text: "Find the odd one out: 2, 5, 10, 17, 27, 37",
      option_a: "10",
      option_b: "17",
      option_c: "27",
      option_d: "37",
      correct_answer: "c",
      explanation: "The pattern is n² + 1: 1+1=2, 4+1=5, 9+1=10, 16+1=17, 25+1=26 (not 27), 36+1=37. So 27 is wrong.",
      subject: "Reasoning",
    },
    {
      id: "hp-5",
      question_text: "हरियाणा राज्य का गठन कब हुआ था?",
      option_a: "1 नवंबर 1966",
      option_b: "15 अगस्त 1966",
      option_c: "26 जनवरी 1966",
      option_d: "1 मई 1966",
      correct_answer: "a",
      explanation: "हरियाणा राज्य का गठन 1 नवंबर 1966 को पंजाब से अलग होकर हुआ था।",
      subject: "Haryana GK",
    },
    {
      id: "hp-6",
      question_text: "The Supreme Court of India was established on:",
      option_a: "26 January 1950",
      option_b: "28 January 1950",
      option_c: "15 August 1947",
      option_d: "26 November 1949",
      correct_answer: "b",
      explanation: "The Supreme Court of India was inaugurated on 28 January 1950.",
      subject: "General Knowledge",
    },
    {
      id: "hp-7",
      question_text: "A train 150m long passes a pole in 15 seconds. What is the speed of the train in km/hr?",
      option_a: "36 km/hr",
      option_b: "40 km/hr",
      option_c: "45 km/hr",
      option_d: "50 km/hr",
      correct_answer: "a",
      explanation: "Speed = Distance/Time = 150/15 = 10 m/s = 10 × 18/5 = 36 km/hr",
      subject: "Math",
    },
    {
      id: "hp-8",
      question_text: "If COMPUTER is coded as RFUVQNPC, then MEDICINE is coded as:",
      option_a: "MFEDJDJO",
      option_b: "ENICJDME",
      option_c: "FNDJDJOF",
      option_d: "ENICIDMF",
      correct_answer: "b",
      explanation: "The pattern reverses the word and shifts each letter by +1. MEDICINE → ENICIDME → ENICJDME",
      subject: "Reasoning",
    },
    {
      id: "hp-9",
      question_text: "'वीर चक्र' से सम्मानित हरियाणा का पहला जवान कौन था?",
      option_a: "मेजर होशियार सिंह",
      option_b: "कैप्टन अभिमन्यु राणा",
      option_c: "सूबेदार योगेंद्र सिंह यादव",
      option_d: "नायक सुरेंद्र सिंह",
      correct_answer: "a",
      explanation: "मेजर होशियार सिंह 'वीर चक्र' से सम्मानित हरियाणा के पहले जवान थे।",
      subject: "Haryana GK",
    },
    {
      id: "hp-10",
      question_text: "'संविधान सभा' के अध्यक्ष कौन थे?",
      option_a: "डॉ. राजेंद्र प्रसाद",
      option_b: "डॉ. बी.आर. अंबेडकर",
      option_c: "पंडित जवाहरलाल नेहरू",
      option_d: "सरदार वल्लभभाई पटेल",
      correct_answer: "a",
      explanation: "डॉ. राजेंद्र प्रसाद संविधान सभा के स्थायी अध्यक्ष थे।",
      subject: "General Knowledge",
    },
  ],
  "haryana-group-d": [
    {
      id: "gd-1",
      question_text: "हरियाणा की राजधानी क्या है?",
      option_a: "गुरुग्राम",
      option_b: "चंडीगढ़",
      option_c: "फरीदाबाद",
      option_d: "पानीपत",
      correct_answer: "b",
      explanation: "चंडीगढ़ हरियाणा और पंजाब दोनों राज्यों की संयुक्त राजधानी है।",
      subject: "Haryana GK",
    },
    {
      id: "gd-2",
      question_text: "हरियाणा में कुल कितने जिले हैं?",
      option_a: "20",
      option_b: "21",
      option_c: "22",
      option_d: "23",
      correct_answer: "c",
      explanation: "हरियाणा में वर्तमान में 22 जिले हैं।",
      subject: "Haryana GK",
    },
    {
      id: "gd-3",
      question_text: "2 + 2 × 2 = ?",
      option_a: "4",
      option_b: "6",
      option_c: "8",
      option_d: "10",
      correct_answer: "b",
      explanation: "BODMAS नियम के अनुसार: पहले गुणा 2 × 2 = 4, फिर जोड़ 2 + 4 = 6",
      subject: "Basic Math",
    },
    {
      id: "gd-4",
      question_text: "भारत का राष्ट्रीय पक्षी कौन सा है?",
      option_a: "कौआ",
      option_b: "मोर",
      option_c: "तोता",
      option_d: "कबूतर",
      correct_answer: "b",
      explanation: "मोर भारत का राष्ट्रीय पक्षी है।",
      subject: "General Awareness",
    },
    {
      id: "gd-5",
      question_text: "अगर किसी महीने की 3 तारीख को सोमवार है, तो उसी महीने की 21 तारीख को कौन सा दिन होगा?",
      option_a: "शुक्रवार",
      option_b: "शनिवार",
      option_c: "रविवार",
      option_d: "सोमवार",
      correct_answer: "a",
      explanation: "3 से 21 = 18 दिन = 2 सप्ताह + 4 दिन। सोमवार + 4 = शुक्रवार",
      subject: "Reasoning",
    },
    {
      id: "gd-6",
      question_text: "हरियाणा का राज्य पशु कौन सा है?",
      option_a: "शेर",
      option_b: "हाथी",
      option_c: "नीलगाय",
      option_d: "काला हिरण",
      correct_answer: "d",
      explanation: "काला हिरण (Black Buck) हरियाणा का राज्य पशु है।",
      subject: "Haryana GK",
    },
    {
      id: "gd-7",
      question_text: "100 का 25% कितना होगा?",
      option_a: "20",
      option_b: "25",
      option_c: "30",
      option_d: "35",
      correct_answer: "b",
      explanation: "100 का 25% = (100 × 25)/100 = 25",
      subject: "Basic Math",
    },
    {
      id: "gd-8",
      question_text: "भारत का संविधान कब लागू हुआ?",
      option_a: "15 अगस्त 1947",
      option_b: "26 नवंबर 1949",
      option_c: "26 जनवरी 1950",
      option_d: "2 अक्टूबर 1950",
      correct_answer: "c",
      explanation: "भारत का संविधान 26 जनवरी 1950 को लागू हुआ।",
      subject: "General Awareness",
    },
    {
      id: "gd-9",
      question_text: "निम्न में से कौन सी संख्या 3 से विभाज्य है?",
      option_a: "124",
      option_b: "235",
      option_c: "126",
      option_d: "238",
      correct_answer: "c",
      explanation: "126 के अंकों का योग 1+2+6 = 9, जो 3 से विभाज्य है।",
      subject: "Basic Math",
    },
    {
      id: "gd-10",
      question_text: "सुल्तानपुर राष्ट्रीय उद्यान हरियाणा के किस जिले में है?",
      option_a: "गुरुग्राम",
      option_b: "फरीदाबाद",
      option_c: "हिसार",
      option_d: "रोहतक",
      correct_answer: "a",
      explanation: "सुल्तानपुर राष्ट्रीय उद्यान गुरुग्राम जिले में स्थित है।",
      subject: "Haryana GK",
    },
  ],
  "haryana-cet": [
    {
      id: "cet-1",
      question_text: "हरियाणा का क्षेत्रफल कितना है?",
      option_a: "44,212 वर्ग किमी",
      option_b: "45,212 वर्ग किमी",
      option_c: "46,212 वर्ग किमी",
      option_d: "47,212 वर्ग किमी",
      correct_answer: "a",
      explanation: "हरियाणा का कुल क्षेत्रफल 44,212 वर्ग किलोमीटर है।",
      subject: "Haryana GK",
    },
    {
      id: "cet-2",
      question_text: "If the ratio of ages of A and B is 3:5 and sum of their ages is 40, find A's age.",
      option_a: "12 years",
      option_b: "15 years",
      option_c: "18 years",
      option_d: "20 years",
      correct_answer: "b",
      explanation: "A's age = (3/8) × 40 = 15 years",
      subject: "Quantitative Aptitude",
    },
    {
      id: "cet-3",
      question_text: "Choose the correct spelling:",
      option_a: "Accomodation",
      option_b: "Acommodation",
      option_c: "Accommodation",
      option_d: "Acomodation",
      correct_answer: "c",
      explanation: "The correct spelling is 'Accommodation' with double 'c' and double 'm'.",
      subject: "English",
    },
    {
      id: "cet-4",
      question_text: "A, B, C, D, E में से कौन सबसे लंबा है? A, B से लंबा है। C, D से छोटा है। E, A से लंबा है। B, D से लंबा है।",
      option_a: "A",
      option_b: "B",
      option_c: "D",
      option_d: "E",
      correct_answer: "d",
      explanation: "क्रम: E > A > B > D > C, इसलिए E सबसे लंबा है।",
      subject: "Reasoning",
    },
    {
      id: "cet-5",
      question_text: "हरियाणा विधानसभा में कुल कितनी सीटें हैं?",
      option_a: "85",
      option_b: "90",
      option_c: "95",
      option_d: "100",
      correct_answer: "b",
      explanation: "हरियाणा विधानसभा में कुल 90 सीटें हैं।",
      subject: "Haryana GK",
    },
    {
      id: "cet-6",
      question_text: "A shopkeeper sells an article for ₹450 at 25% profit. Find the cost price.",
      option_a: "₹320",
      option_b: "₹340",
      option_c: "₹360",
      option_d: "₹380",
      correct_answer: "c",
      explanation: "CP = SP × 100/(100 + Profit%) = 450 × 100/125 = ₹360",
      subject: "Quantitative Aptitude",
    },
    {
      id: "cet-7",
      question_text: "Select the correct passive voice: 'She is writing a letter.'",
      option_a: "A letter is written by her",
      option_b: "A letter is being written by her",
      option_c: "A letter was being written by her",
      option_d: "A letter has been written by her",
      correct_answer: "b",
      explanation: "Present Continuous passive: Object + is/are + being + V3 + by + Subject",
      subject: "English",
    },
    {
      id: "cet-8",
      question_text: "यदि किसी कोड में BASKET को UFLTBC लिखा जाता है, तो FLOWER को कैसे लिखेंगे?",
      option_a: "SFXPMG",
      option_b: "SFXPGM",
      option_c: "SFWPMG",
      option_d: "SFWPGM",
      correct_answer: "a",
      explanation: "प्रत्येक अक्षर को उल्टा करके +1 जोड़ा गया है। FLOWER → REWOLF → SFXPMG",
      subject: "Reasoning",
    },
    {
      id: "cet-9",
      question_text: "कुरुक्षेत्र में किस महाभारत युद्ध का मैदान स्थित है?",
      option_a: "ज्योतिसर",
      option_b: "पानीपत",
      option_c: "थानेसर",
      option_d: "पिपली",
      correct_answer: "a",
      explanation: "ज्योतिसर कुरुक्षेत्र में स्थित वह स्थान है जहाँ भगवान कृष्ण ने अर्जुन को गीता का उपदेश दिया था।",
      subject: "Haryana GK",
    },
    {
      id: "cet-10",
      question_text:
        "A can do a work in 12 days and B can do it in 18 days. In how many days can they complete it together?",
      option_a: "6.2 days",
      option_b: "7.2 days",
      option_c: "8.2 days",
      option_d: "9.2 days",
      correct_answer: "b",
      explanation: "Combined work = 1/12 + 1/18 = 5/36. Days = 36/5 = 7.2 days",
      subject: "Quantitative Aptitude",
    },
  ],
}

export function getDemoTest(testId: string) {
  const questions = demoQuestions[testId]
  if (!questions) return null

  const testInfo: Record<string, { title: string; duration: number }> = {
    "haryana-police": { title: "Haryana Police Constable Demo Test", duration: 10 },
    "haryana-group-d": { title: "Haryana Group D Demo Test", duration: 10 },
    "haryana-cet": { title: "Haryana CET Demo Test", duration: 10 },
  }

  return {
    id: testId,
    title: testInfo[testId]?.title || "Demo Test",
    duration: testInfo[testId]?.duration || 10,
    questions,
  }
}
